language: java

services:
  - docker

before_install:
  - docker pull levelrin/eurekatext:init

script:
  - docker run --rm -v $(pwd)/build:/usr/src/myapp/build levelrin/eurekatext:init

after_success:
  - bash <(curl -s https://codecov.io/bash)
